add footer
the-perch/one-cloud pull request #3
Opened 2019-06-09 15:27 UTC by VladmaxPower

2019-06-10 19:48 UTC, haos616 requested changes

2019-06-10 19:48 UTC, haos616 commented on index.html
> +    <link href="css/reset.css" rel="stylesheet">
Думаю, `reset.css` стоит в начало добавить =)

2019-06-10 19:48 UTC, haos616 commented on index.html
> +    <div class="social_link">
@olivervaz @VladmaxPower @skrnvn  Нам надо соглосовать именование. Вот вариант https://ru.bem.info/methodology/naming-convention/

2019-06-11 16:28 UTC, haos616 approved these changes

2019-06-12 07:40 UTC, olivervaz approved these changes

2019-06-17 19:36 UTC, skrnvn approved these changes

2019-06-18 16:55 UTC, merged