add feature posts
the-perch/one-cloud pull request #4
Opened 2019-06-10 14:27 UTC by VladmaxPower

2019-06-10 19:58 UTC, haos616 requested changes

2019-06-10 19:58 UTC, haos616 commented on css/core.css
> +}
Что бы при мёрже git лучше понимал как смёржить надо ставить пустую стору в конце.

2019-06-10 19:58 UTC, haos616 commented on css/feature_posts.css
> +}
Тоже самое

2019-06-10 19:58 UTC, haos616 commented on index.html
> +			<h2 class="title feature_posts-title">FEATURE POSTS</h2>
Думаю лучше трансформировать текст с помощью css а исначальо написать `Feature posts`

2019-06-11 16:30 UTC, haos616 approved these changes

2019-06-12 07:41 UTC, olivervaz approved these changes

2019-06-17 19:37 UTC, skrnvn approved these changes

2019-06-18 13:04 UTC, merged