Feature/header
the-perch/one-cloud pull request #6
Opened 2019-06-10 20:46 UTC by olivervaz

without scrolling/ will be added later

2019-06-11 07:45 UTC, haos616 requested changes

2019-06-11 07:45 UTC, haos616 commented on template/header.html
> +<header>
Я думаю можно это перенести в `index.html`

2019-06-11 07:45 UTC, haos616 commented on template/header.html
> +        <h2>WITHOUT TAKING POWER VIOLENTLY</h2>
Лучше трансформировать тескт с помощью css. В дальшейшем так проще делать изменения.

2019-06-11 07:45 UTC, haos616 commented on template/header.html
> +        <button class="section-main-slogan-btn">Full view</button>
Я бы не советовал называть стил привязываясь к его назначению, особенно для кнопок и ссылок. Подобный стиль может появиться где-то еще и тогда название не будет логично. Например в bootstrap (https://getbootstrap.com/docs/4.3/components/buttons/) есть модификаторы для кнопок. Для модификации размера и визуального вида. В основном есть `primary` и `secondary`:
```html
<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-secondary">Secondary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-warning">Warning</button>
<button type="button" class="btn btn-info">Info</button>
<button type="button" class="btn btn-light">Light</button>
<button type="button" class="btn btn-dark">Dark</button>
```

2019-06-11 07:45 UTC, haos616 commented on template/header.html
>  </html>
И настоятельно рекомендую не забывать ставить пустую строку, так git-у проще понять как мёржить код. В редакторах иногда есть флажок который будет делать это автоматически.

2019-06-11 12:07 UTC, olivervaz commented on template/header.html
> +<header>
ok я потом создам пул где добавлю все в html.

2019-06-11 16:26 UTC, haos616 approved these changes

2019-06-11 16:45 UTC, VladMaxPower approved these changes

2019-06-17 19:35 UTC, skrnvn approved these changes

2019-06-18 17:06 UTC, merged